image: ascot5pyv2


build:   
    script:
        - cd a5py 
        - python setup.py build

install:   
    script:
        - cd a5py 
        - pip install -e .

wheel:
    script:
        - cd a5py
        - pip install build
        - python -m build --wheel
    artifacts:
        paths:
            - a5py/dist/a5py-0.0-py3-none-any.whl

test_libascot:
    script:
        - 'cd a5py'
        - 'curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN"  "https://version.aalto.fi/gitlab/api/v4/projects/52/jobs/artifacts/256-refactor_ascot5_main/raw/libascot.so?job=compile_libascot" --output /usr/lib/libascot.so'
        - 'curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN"  "https://version.aalto.fi/gitlab/api/v4/projects/52/jobs/artifacts/256-refactor_ascot5_main/raw/ascotpy2.py?job=compile_libascot" --output a5py/ascotpy/ascotpy2.py'
        - pip install -e .

tests:
    script:
        - cd a5py
        - 'curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN"  "https://version.aalto.fi/gitlab/api/v4/projects/52/jobs/artifacts/256-refactor_ascot5_main/raw/libascot.so?job=compile_libascot" --output /usr/lib/libascot.so'
        - 'curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN"  "https://version.aalto.fi/gitlab/api/v4/projects/52/jobs/artifacts/256-refactor_ascot5_main/raw/ascotpy2.py?job=compile_libascot" --output a5py/ascotpy/ascotpy2.py'
        - pip install scipy
        - pip install matplotlib
        - pip install scikit-image
        - pip install -e .
        - cd ..
        - python a5py/a5py/preprocessing/simpleruns.py
        - ls -lh *.h5
        - python a5py/a5py/examples/running_through_python.py
        - ls -lh *.h5
        - 'curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN"  "https://version.aalto.fi/gitlab/api/v4/projects/52/jobs/artifacts/256-refactor_ascot5_main/raw/ascot5_main?job=compile_ascot5_main" --output ascot5_main'
        - chmod u+x ascot5_main
        - '#./ascot5_main --in helloworld.h5 --out helloworld_output.h5'
        - python a5py/a5py/testascot/test_ascot.py init
        - python a5py/a5py/testascot/test_ascot.py run
        - python a5py/a5py/testascot/test_ascot.py check
        - ls -lh
