compile_ascot5_main:
  tags:
    - docker-images
  image: ascot5v2dep
  only:
    - master
    - develop
  script: "make ascot5_main FLAGS=-foffload=disable"

compile_ascot5_main_all:
  tags:
    - docker-images
  image: ascot5v2dep
  script:
    - make ascot5_main FLAGS=-foffload=disable

compile_ascot5_main_MPI:
  tags:
    - docker-images
  image: ascot5v2dep
  script:
    - make ascot5_main MPI=1 FLAGS=-foffload=disable
