name: (Reusable) Build
on: [workflow_call]

jobs:

  check:
    name: Is-Image-Outdated
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker:
              - './Dockerfile'
              - './requirements'

  Build-Image:
    needs: check
    if: ${{ needs.check.outputs.docker == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build ./ --tag ghcr.io/ascot4fusion/ascot5deps:latest
          docker run ghcr.io/ascot4fusion/ascot5deps:latest
          docker push ghcr.io/ascot4fusion/ascot5deps:latest

  Build-Code:
    needs: Build-Image
    if: always() || failure()
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ascot4fusion/ascot5deps:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Make ascot5_main with MPI
        run: make ascot5_main MPI=1 FLAGS="-foffload=disable"

      - name: Make clean
        run: make clean

      - name: Make ascot5_main without MPI
        run: make ascot5_main MPI=0 FLAGS="-foffload=disable"

      - name: Make libascot.so
        run: make libascot MPI=0 FLAGS="-foffload=disable"

      - name: Make BBNBI
        run: make bbnbi5 MPI=0 FLAGS="-foffload=disable"

      - name: Make ascot2py
        run: make ascot2py.py MPI=0 FLAGS="-foffload=disable"

      - name: Set permissions and pack
        run: |
          cd ./build
          chmod +x ascot5_main bbnbi5
          tar -cf code.tar ascot5_main bbnbi5 libascot.so
          cd ..

      - name: Upload code
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: ./build/code.tar

      - name: Upload ascot2py.py
        uses: actions/upload-artifact@v3
        with:
          name: ascot2py
          path: ./a5py/ascotpy/ascot2py.py
