name: Run Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  Prepare:
    permissions:
      contents: read
      packages: write
    uses: ascot4fusion/ascot5/.github/workflows/build.yaml@main

  Testing:
    needs: Prepare
    permissions:
      contents: read
    uses: ascot4fusion/ascot5/.github/workflows/tests.yaml@main
    with:
      run_unit_tests: true
      run_physics_tests: true

  Docs:
    needs: Prepare
    permissions:
      contents: read
      packages: read
      pages: write
      id-token: write
    uses: ascot4fusion/ascot5/.github/workflows/docs.yaml@main
